org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Djavax.net.ssl.trustStore=C:/Users/franc/Documents/GitHub/ServiceHub/ServiceHub/android-spen/.ssl/truststore.jks -Djavax.net.ssl.trustStorePassword=changeit
android.useAndroidX=true
android.nonTransitiveRClass=true
org.gradle.java.home=C:\\Program Files\\Android\\Android Studio\\jbr
